--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WavyCraft/WavyCasino
build-by-default: true
branches:
- main
projects:
  WavyCasino:
    path: ""
    libs:
       - src: terpz710/pocketforms/PocketForms
         version: ^1.0.0
       - src: Terpz710/libMessages/libMessages
         version: ^1.0.0
       - src: ACM-PocketMine-MP/Commando/Commando
         version: ^3.2.1
    lint: false
...
